version: '2'
services:
  commande-db:
    container_name: commande-db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=dev
  commande-db-prod:
    container_name: commande-db-prod
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=prod
  commande:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: commande
    image: commande
    ports:
      - "10000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: integration
